version: '3.8'

services:
  suaraunpad-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: suaraunpad-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped